### ISSUE TITLE
Support for sub-regions

### ISSUE THREAD

**Issue by adamcooke** [adamcooke/vat-rates#18]
Some countries have regions which charge different rates of VAT. Portugal & Spain are the main examples of this. The DSL should support this as so:

``` ruby
country do

  name 'Portugal'
  code 'PT'
  country_code 'PT'

  period do
    rate :reduced1, 6
    rate :reduced2, 13
    rate :standard, 23
    rate :parking, 13
  end

  region do 
    name 'Azores'
    period do
      rate :standard, 18
    end
  end

end
```

How applications will use this data is unknown. Perhaps just a basic case insensitive lookup based on the last line of the address or the state/county provided by the user? I will leave this up to the individual consumers of the JSON to decide how they wish to implement this.

**Comment by kdeldycke** [comment]
I compiled a list of sub-territories and their applicable VAT rates. See: https://github.com/kdeldycke/vat-rates
