### ISSUE TITLE
Why a webservice?

### ISSUE THREAD

**Issue by vanderhoorn** [adamcooke/vat-rates#19]
I like the idea of a gem that stores all the VAT rates.

But I was wondering why the choice for a web service? Why not something like the tzinfo gem https://github.com/tzinfo/tzinfo which allows me to use timezones without having to make a connection to a webserver? In general, I prefer avoiding making (expensive) calls to external services.

**Comment by adamcooke** [comment]
I prefer not having to deploy/upgrade my web apps just because a VAT rate changes.

However, you can just add this gem to your application and access the rates directly. 

```ruby
require 'vat_rates'
VATRates.countries  #=> returns an array
```

**Comment by vanderhoorn** [comment]
> I prefer not having to deploy/upgrade my web apps just because a VAT rate changes.

Nobody does, but a VAT rate changes on average every 4-5 years?

**Comment by adamcooke** [comment]
As I said, you don't have to use the web service :smile:
