### ISSUE TITLE
Update rates from ec.europa.eu

### ISSUE THREAD

**Issue by hakanensari** [adamcooke/vat-rates#23]
Hi @adamcooke,

Thanks so much for the API and MOSS-related work. Based on a brief exchange with the VAT folks at @alphagov, it seems the canonical source for current and historical rates is:

http://ec.europa.eu/taxation_customs/tic/public/vatRates/vatratesSearch.html

I'm not sure how `reduced1` and so on correspond to the entries on that page, which are:

* Standard
* Broadcasting Services - Radio and TV programmes
* Telecommunication & e-Services

I'm assuming your source is something else. Perhaps you could explain or rethink your schema based on this?

Also, a daily, scheduled update scraping the above URL would ensure the site is up-to-date. I do something similar with the [European Central Bank](http://fixer.io) and can pitch in if you want. I didn't find your email on your website so figured I'll post here.

**Comment by adamcooke** [comment]
The data provided on this site doesn't actually appear to be as up to date as one would hope.
