### ISSUE TITLE
Czech Republic / Missing reduced rate

### ISSUE THREAD

**Issue by stayhero** [adamcooke/vat-rates#27]
According to http://ec.europa.eu/taxation_customs/resources/documents/taxation/vat/how_vat_works/rates/vat_rates_en.pdf there is a reduced rate of 10% available in Czech Republic.

Therefore the rate "reduced" should be removed and replaced by "reduced_1" (10%) and "reduced_2" (15%). Is that right? 

Or do you rather want to keep "reduced" as 15% and add a new rate "reduced_1" with 10%?

**Comment by frogggias** [comment]
reduced1=15%
reduced2=10%
Should be right solution
