### ISSUE TITLE
Greece raised VAT rate to 24%

### ISSUE THREAD

**Issue by pl-jankowskimichal** [adamcooke/vat-rates#28]
They did that on 1st June 2016, could you please update your data?
Source:
http://www.vatlive.com/european-news/greece-raises-vat-rate-to-24-2017

Best regards,
Michał

**Comment by pl-jankowskimichal** [comment]
Pull request pending. :)

**Comment by stayhero** [comment]
👍  for the update.

Some additional sources:

http://sputniknews.com/europe/20160601/1040602396/greece-vat-tax-eu.html
http://www.huffingtonpost.com/david-c-wittig/greece-has-a-deal--of-sor_b_10239932.html

Unfortunately not yet updated at http://ec.europa.eu

**Comment by dannyvankooten** [comment]
Closed by #29, in case someone is wondering whether this was merged yet. :)
