### ISSUE TITLE
Dead project

### ISSUE THREAD

**Issue by samupl** [adamcooke/vat-rates#34]
Is this project dead? It looks like it hasn't been updated for a very long while, and vat rates have since changed. Are there any plans to continue support for this package? If not, is there any viable alternative?

**Comment by skington** [comment]
Which VAT rates have changed?

**Comment by Fjan** [comment]
I did a check earlier this year and the high VAT rates seemed to be all correct (have not checked the reduced VAT rates)

**Comment by samupl** [comment]
I may have jumped into conclusion that the project is dead, but some rates seem to not be updated for a while. 

For example, Czech republic. Current version on http://jsonvat.com/:

```javascript
{
    name: "Czech Republic",
    code: "CZ",
    country_code: "CZ",
    periods: [
        {
            effective_from: "0000-01-01",
            rates: {
                reduced: 15,
                standard: 21
            }
        }
    ]
}
```

But according to https://www.vatlive.com/vat-rates/european-vat-rates/ - there is also a second reduced rate of 10%.

Greece current reduced2 is 13.0%, but on jsonvat.com it says it's 13.5%.

**Comment by ihatemornings** [comment]
I'd be interested to know if this project is still alive too. I've found it useful as one of a few sources that help me keep on top of rate changes (along with RSS feeds from VATLive and wikipedia::VAT).

**Comment by Mark-H** [comment]
It's an open source project. If rates are missing or out of date, send a pull request to help yourself and everyone else that depends on it :)

**Comment by ihatemornings** [comment]
@Mark-H Totally. But there are three outstanding pull requests that haven't moved in ages. At least two of them seem non-controversial. I think that's what makes the project seem dormant and maybe puts people off contributing.

**Comment by Mark-H** [comment]
As an open source maintainer, I am extremely put off by people asking if projects are dead or dormant. Life happens and can sometimes make things slip a little, so sometimes all it takes is a constructive or helpful comment to get things moving. #31 had a question of sources for the change, so I've just looked that up and verified they are indeed correct.

**Comment by samupl** [comment]
I wouldn't consider these types of questions to be offending. In my opinion it's better to ask than to spawn dozens of forks claiming to be the "continuation of dead project XXX", and then struggle to catch up. So don't take my questions as any form of attack :)

**Comment by adamcooke** [comment]
It isn't dead. We use it ourselves (although we only charge standard rates so that's all I usually notice when they change). As far as I know, things are up to date. If not, pull requests are welcome as long as updates come with suitable sources so I can verify the new changes. Pull requests that don't include links to sources are just extra work and easily ignored.

The france pull request seems to only change historical rates.
The czech one didn't add a new period and just updated the default one (and only affect reduced rates).

**Comment by adamcooke** [comment]
To be honest, managing rates other than standard is quite hard work and I don't actually know how that data could be consumed by applications without adding their own logic about which rate to charge in each country.

**Comment by Mark-H** [comment]
Yeah, dealing with taxes is fun ;) 

For my MODX ecommerce plugin ([Commerce](https://www.modmore.com/commerce/)) I managed to build a system that has tax groups (each unique product is assigned to one, so you may have a "Clothing" tax group for example that's assigned to shirts), which then contains cascading tax rules that can do different things depending on the customer. So it'll have rules like "if customer is in the Netherlands, apply the Dutch standard VAT rate", followed by "if customer is in the EU, apply their local standard VAT rate", and "else apply a 0% tax". So people that have complex tax needs can configure it in a (relatively) straightforward way. It also has a checkbox to support the reverse charge, which of course changes all the rules 😬 

Got plenty of grey hairs designing that system, but so far it's holding up well to the real world... 

JSONVAT.com is used in that system as the source for the EU rates, so thanks for making that available. If you add a donate button somewhere I'll buy you a coffee/beer 🍻
