### ISSUE TITLE
jsonvat.com expired

### ISSUE THREAD

**Issue by gionn** [adamcooke/vat-rates#40]
http://jsonvat.com/

> This domain (jsonvat.com) expired on 13/10/2019. You can retrieve your domain by clicking here.

**Comment by gionn** [comment]
ref https://github.com/adamcooke/json-vat/issues/15

**Comment by Mark-H** [comment]
@adamcooke If you can renew the domain I'm happy to sponsor the domain registration for a couple of years. mark@modmore.com

**Comment by adamcooke** [comment]
This has now been renewed. Sorry for any problems! Entirely my fault for not noticing the e-mail about its impending doom.
